/*
    날짜 : 2025/07/17
    이름 : 한탁원
    내용 : 5장 데이터베이스 객체
*/

// 실습하기 3-2. 인덱스 조회\
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;

// 실습하기 3-3. 인덱스 생성
CREATE INDEX IDX_USER1_ID ON USER1(ID);
SELECT * FROM USER_IND_COLUMNS; ☞

// 실습하기 3-4. 인덱스 삭제
DROP INDEX IDX_USER1_ID;
SELECT * FROM USER_IND_COLUMNS;

-- 실습하기 3-5
CREATE VIEW VW_USER1 AS (SELECT NAME, HP, AGE FROM USER1);
CREATE VIEW VW_USER2_AGE_UNDER30 AS (SELECT * FROM USER2 WHERE AGE < 30);

-- 실습하기 3-6
DROP TABLE USER6;
CREATE TABLE USER6 (
    SEQ NUMBER PRIMARY KEY,
    NAME VARCHAR2(20),
    GENDER CHAR(1),
    AGE NUMBER,
    ADDR VARCHAR2(255)
);

--실습하기 3-10
CREATE SEQUENCE SEQ_USER6 INCREMENT BY 1 START WITH 1;

-- 실습하기 3-11
INSERT INTO USER6 (SEQ, NAME, GENDER, AGE, ADDR)
VALUES (SEQ_USER6.NEXTVAL, '김유신', 'M', 25, '김해시');
INSERT INTO USER6 VALUES (SEQ_USER6.NEXTVAL, '김춘추', 'M', 23, '경주시');
INSERT INTO USER6 VALUES (SEQ_USER6.NEXTVAL, '신사임당', 'F', 27, '강릉시');

